config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'demo', to: 'static_pages#demo'
  get 'team', to: 'static_pages#team'
  get 'career', to: 'static_pages#career'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create 
  end
  
  resources :lessons, only: [:show, :update]
  namespace :instructor do
    resources :lessons, only: [:update, :destroy]
    resources :sections, only: [:update, :destroy] do
      resources :lessons, only: [:create, :destroy]
    end
    resources :courses, only: [:new, :create, :show, :destroy, :index] do
      resources :sections, only: [:create]
    end
  end
end# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader 

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
        
  devise :database_authenticatable, :registerable, :recoverable, 
         :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

  def admin?
    @admin = User.find_by(:admin => true)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
     # Uncomment the section below if you want users to be created if they don't exist
      unless user
          user = User.create(
             email: data["email"],
             password: Devise.friendly_token[0,20]
          )
      end
    user
  end
           
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def create
    @user = User.new(:email)

    if @user.save
      ModelMailer.new_user_notification(@user).deliver
      format.html { redirect_to @user }
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?

        # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premo Content',
        currency: 'usd'
      )
    end

  current_user.enrollments.create(course: current_course)  
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user_enrolled? unless :user_admin?
  def show
    current_lesson
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated'
  end

  private

  def authenticate_user_enrolled?
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(@current_course), alert: "You Must Enroll to View!"
    end
  end

  def user_admin?
    if current_user.find(params[:admin]) == true
      redirect_to course_path
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:row_order_position)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end

  def demo
  end

  def team
  end

  def career
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://vjs.zencdn.net/7.1.0/video-js.css" rel="stylesheet">
  </head>

  <body>
      <div id="flex-content-container">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
          <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <%= link_to 'FitBel', root_url, class: 'navbar-brand' %>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item">
                <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
              </li>
            </ul>
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Demo', demo_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign up!', new_user_registration_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
        
        <% if notice.present? %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>

        <% if alert.present? %>  
          <p class="alert alert-danger"><%= alert %></p>
        <% end %> 

        <%= yield %>
      </div>
      
      <div id="footer">
        <div class="container">
          <div class="row">
           
            <% if user_signed_in? && current_user.admin? %>
            <div class="col-12 col-sm-3">
              <b>Teachers</b>
                <br />
                <%= link_to 'Teach a Course', new_instructor_course_path %>
                <br />  
              <%= link_to 'My Dashboard', dashboard_path %>
            </div>
            <div class="col-12 col-sm-3">
              <b>About</b>
              <br />
              <%= link_to 'Team', team_path %>
              <br />
              <%= link_to 'Careers', career_path %>
              <br />
              <%= link_to 'Demo', demo_path %>
          </div>
          <div class="col-12 col-sm-3"> 
            <b>Contact</b>
            <br />
            wilbobraggins@gmail.com
            <br />
            1340 SE 89th ave
            <br />
            Portland OR, 97214
          </div>
          <div class="col-12 col-sm-3 social">
            <b>Social</b>
            <br />
            <br />
            <%= link_to 'https://github.com/wilbobraggins' do %>
              <span class="fa fa-github-square fa-2x social-button"></span>
            <% end %>  
          
            <%= link_to 'https://www.instagram.com/tinyhousetruck/' do %>
              <span class="fa fa-instagram fa-2x social-button"></span> 
            <% end %>  
            <span class="fa fa-twitter-square fa-2x social-button"></span>
          </div>
          <% else %>
          <div class="row">
            <%= link_to 'My Dashboard', dashboard_path %>
            <div class="col-12 col-sm-4">
              <b>About</b>
              <br />
              <%= link_to 'Team', team_path %>
              <br />
              <%= link_to 'Careers', career_path %>
              <br />
              <%= link_to 'Demo', demo_path %>
            </div>
          </div>
            <div class="col-12 col-sm-4"> 
              <b>Contact</b>
              <br />
              wilbobraggins@gmail.com
              <br />
              1340 SE 89th ave
              <br />
              Portland OR, 97214
            </div>
            <div class="col-12 col-sm-4 social">
              <b>Social</b>
              <br />
              <br />
              <%= link_to 'https://github.com/wilbobraggins' do %>
                <span class="fa fa-github-square fa-2x social-button"></span>
              <% end %>  
            
              <%= link_to 'https://www.instagram.com/tinyhousetruck/' do %>
                <span class="fa fa-instagram fa-2x social-button"></span> 
              <% end %>  
              <span class="fa fa-twitter-square fa-2x social-button"></span>
            </div>

          <% end %>
        </div>
      </div>
    </div>

      <script src="https://vjs.zencdn.net/7.1.0/video.js"></script>
      <script>setTimeout(function(){
              $(".alert").each(function(index){
                  $(this).delay(200*index).fadeTo(1500,0).slideUp(500,function(){
                      $(this).remove();
                      });
                  });
              },2000);
      </script>
       
 
  </body>
</html>